// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGameStore.Contexts;

namespace MyGameStore.Migrations
{
    [DbContext(typeof(MyGameStoreContext))]
    [Migration("20211119102801_updateMigration")]
    partial class updateMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyGameStore.Entities.Person", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("StoreWhereEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("StoreWhereEmployeeId");

                    b.ToTable("tblPeople", "Person");

                    b.HasData(
                        new
                        {
                            id = 0,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "astrid@wittingkulas.name",
                            FirstName = "Korbin",
                            Gender = 0,
                            LastName = "Littel"
                        },
                        new
                        {
                            id = 1,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alfonso.nitzsche@abernathy.biz",
                            FirstName = "Angelita",
                            Gender = 0,
                            LastName = "Haag"
                        },
                        new
                        {
                            id = 2,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rosie_murray@shields.uk",
                            FirstName = "Shayne",
                            Gender = 0,
                            LastName = "Gleason"
                        },
                        new
                        {
                            id = 3,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kyla_ebert@koeppprice.ca",
                            FirstName = "Alva",
                            Gender = 0,
                            LastName = "Kulas"
                        },
                        new
                        {
                            id = 4,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucio_shields@gottlieb.biz",
                            FirstName = "Jadon",
                            Gender = 0,
                            LastName = "Price"
                        },
                        new
                        {
                            id = 5,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lavern@douglas.info",
                            FirstName = "Morton",
                            Gender = 0,
                            LastName = "Armstrong"
                        },
                        new
                        {
                            id = 6,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "theresa@anderson.biz",
                            FirstName = "Rosalia",
                            Gender = 0,
                            LastName = "Harvey"
                        },
                        new
                        {
                            id = 7,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "letha@fahey.biz",
                            FirstName = "Nikolas",
                            Gender = 0,
                            LastName = "Miller"
                        },
                        new
                        {
                            id = 8,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "verlie.hand@wiza.com",
                            FirstName = "Kari",
                            Gender = 0,
                            LastName = "Erdman"
                        },
                        new
                        {
                            id = 9,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "matilda.gibson@mitchell.co.uk",
                            FirstName = "Terry",
                            Gender = 0,
                            LastName = "Hartmann"
                        },
                        new
                        {
                            id = 10,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "clara@gradygulgowski.com",
                            FirstName = "Abby",
                            Gender = 0,
                            LastName = "Howell"
                        },
                        new
                        {
                            id = 11,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "francis_denesik@wehnerrunolfsson.co.uk",
                            FirstName = "Lorenz",
                            Gender = 0,
                            LastName = "Witting"
                        },
                        new
                        {
                            id = 12,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kianna@wiza.info",
                            FirstName = "Chad",
                            Gender = 0,
                            LastName = "Mayert"
                        },
                        new
                        {
                            id = 13,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "javonte@kris.uk",
                            FirstName = "Chad",
                            Gender = 0,
                            LastName = "Larkin"
                        },
                        new
                        {
                            id = 14,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joey@hettinger.biz",
                            FirstName = "Walker",
                            Gender = 0,
                            LastName = "Nicolas"
                        },
                        new
                        {
                            id = 15,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "irving_ondricka@kulaswehner.ca",
                            FirstName = "Leanna",
                            Gender = 0,
                            LastName = "Durgan"
                        },
                        new
                        {
                            id = 16,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ada_keebler@zieme.us",
                            FirstName = "Wilfrid",
                            Gender = 0,
                            LastName = "Emmerich"
                        },
                        new
                        {
                            id = 17,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "megane.rogahn@heaney.name",
                            FirstName = "Myrtie",
                            Gender = 0,
                            LastName = "Crist"
                        },
                        new
                        {
                            id = 18,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ulises@conroy.co.uk",
                            FirstName = "Heloise",
                            Gender = 0,
                            LastName = "McClure"
                        },
                        new
                        {
                            id = 19,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "walker@graham.biz",
                            FirstName = "Tanya",
                            Gender = 0,
                            LastName = "Langworth"
                        });
                });

            modelBuilder.Entity("MyGameStore.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsFranchiseStore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("city")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Place");

                    b.HasKey("Id");

                    b.ToTable("tblStores", "Store");
                });

            modelBuilder.Entity("MyGameStore.Entities.Person", b =>
                {
                    b.HasOne("MyGameStore.Entities.Store", "StoreWhereEmployee")
                        .WithMany("Employees")
                        .HasForeignKey("StoreWhereEmployeeId");

                    b.Navigation("StoreWhereEmployee");
                });

            modelBuilder.Entity("MyGameStore.Entities.Store", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
